"""Saraswati Kahan Hai? - the Dharavi story mission's dialogue.

Shankar comes to Mumbai from his village to find his wife Saraswati, who stopped writing three months
ago. From the blue lane where she rented a room he follows the trail: Lakshmi Tai, the kids' cricket and
Chhotu, Kamla Mausi at the sabzi mandi, Pappu's chai tapri on the main road, tailing Bhau's man Raghu to
the Ganesh pandal, and a race through the monsoon night to the station before Bhau's men get there.

Each scene: (speaker, listener, roman subtitle, devanagari for the voice, gesture, shot)
  speaker / listener: player, vo (Shankar thinking), lakshmi, chhotu, kamla, pappu, raghu, bhau, saraswati
  gesture: Talk, Angry, Cheer, Throw, Drink, Locomotion ('' = Talk)
  shot: '' (over the shoulder onto the speaker), two, wide, close, follow, high, keep
"""

VOICES = {   # edge-tts voice, pitch, rate
    "player": ("hi-IN-MadhurNeural", "-4Hz", "-4%"),
    "vo": ("hi-IN-MadhurNeural", "-8Hz", "-14%"),
    "lakshmi": ("hi-IN-SwaraNeural", "-14Hz", "-8%"),
    "chhotu": ("hi-IN-MadhurNeural", "+62Hz", "+14%"),
    "kamla": ("hi-IN-SwaraNeural", "-24Hz", "+4%"),
    "pappu": ("hi-IN-MadhurNeural", "+12Hz", "+12%"),
    "raghu": ("hi-IN-MadhurNeural", "-14Hz", "+4%"),
    "bhau": ("hi-IN-MadhurNeural", "-26Hz", "-12%"),
    "saraswati": ("hi-IN-SwaraNeural", "+4Hz", "-4%"),
}

SCENES = {
    # sunset on Marine Drive: Shankar on the sea wall, thinking of her (cameras are placed in the level script)
    "marine": [
        ("vo", "", "Bambai... kehte hain yeh shehar kabhi nahi sota. Aaj mujhe bhi neend nahi aayegi.",
         "बम्बई... कहते हैं ये शहर कभी नहीं सोता। आज मुझे भी नींद नहीं आएगी।", "", ""),
        ("vo", "", "Saraswati ko samundar bahut pasand tha. Kehti thi, ek din tumhe Marine Drive le chalungi.",
         "सरस्वती को समुंदर बहुत पसंद था। कहती थी, एक दिन तुम्हें मरीन ड्राइव ले चलूँगी।", "", ""),
        ("vo", "", "Aaj main yahan hoon... aur woh nahi.",
         "आज मैं यहाँ हूँ... और वो नहीं।", "", ""),
        ("vo", "", "Gaon se jaate waqt usne mera haath pakad ke kaha tha - bas kuch mahine, Shankar. Thoda paisa jod loon, phir apna ghar banayenge.",
         "गाँव से जाते वक़्त उसने मेरा हाथ पकड़ के कहा था - बस कुछ महीने, शंकर। थोड़ा पैसा जोड़ लूँ, फिर अपना घर बनाएँगे।", "", ""),
        ("vo", "", "Teen mahine ho gaye. Na koi phone, na koi chitthi.",
         "तीन महीने हो गए। न कोई फ़ोन, न कोई चिट्ठी।", "", ""),
        ("vo", "", "Uski aakhri chitthi mein bas itna likha tha... Dharavi. Neeli gali. Lakshmi Tai ka ghar.",
         "उसकी आख़िरी चिट्ठी में बस इतना लिखा था... धारावी। नीली गली। लक्ष्मी ताई का घर।", "", ""),
        ("vo", "", "Log kehte hain, Bambai logon ko nigal jaati hai.",
         "लोग कहते हैं, बम्बई लोगों को निगल जाती है।", "", ""),
        ("vo", "", "Main nahi maanta. Main use dhoondh ke rahunga.",
         "मैं नहीं मानता। मैं उसे ढूँढ के रहूँगा।", "", ""),
        ("vo", "", "Kal subah... Dharavi jaake dhoondta hoon.",
         "कल सुबह... धारावी जाके ढूँढता हूँ।", "", ""),
    ],
    "lane_arrive": [
        ("vo", "", "Neeli gali... Lakshmi Tai ka ghar yahin kahin hoga.",
         "नीली गली... लक्ष्मी ताई का घर यहीं कहीं होगा।", "", "follow"),
    ],
    "lakshmi": [
        ("player", "lakshmi", "Namaste Tai. Main Shankar... Saraswati ka pati. Gaon se aaya hoon.",
         "नमस्ते ताई। मैं शंकर... सरस्वती का पति। गाँव से आया हूँ।", "", "two"),
        ("lakshmi", "player", "Shankar? Arre baap re! Saraswati din raat tumhari hi baatein karti thi.",
         "शंकर? अरे बाप रे! सरस्वती दिन रात तुम्हारी ही बातें करती थी।", "", ""),
        ("player", "lakshmi", "Woh kahan hai Tai? Teen mahine se uski koi khabar nahi.",
         "वो कहाँ है ताई? तीन महीने से उसकी कोई ख़बर नहीं।", "", ""),
        ("lakshmi", "player", "Wahi to... das din pehle achanak kamra chhod ke chali gayi. Bahut dari hui thi bechari.",
         "वही तो... दस दिन पहले अचानक कमरा छोड़ के चली गई। बहुत डरी हुई थी बेचारी।", "", "close"),
        ("player", "lakshmi", "Dari hui? Kis se?",
         "डरी हुई? किस से?", "", "close"),
        ("lakshmi", "player", "Mujhe nahi pata beta. Par gali ke aage maidan mein bachche cricket khelte hain. Chhotu ne usse aakhri baar dekha tha.",
         "मुझे नहीं पता बेटा। पर गली के आगे मैदान में बच्चे क्रिकेट खेलते हैं। छोटू ने उसे आख़िरी बार देखा था।", "", ""),
        ("lakshmi", "player", "Jao, usse poochho. Aur haan... sambhal ke rehna. Yeh Bambai hai.",
         "जाओ, उससे पूछो। और हाँ... सँभल के रहना। ये बम्बई है।", "", "close"),
    ],
    "chhotu": [
        ("chhotu", "player", "Thank you bhaiya! Ball naali mein jaati to mummy bahut maarti.",
         "थैंक यू भैया! बॉल नाली में जाती तो मम्मी बहुत मारती।", "Cheer", "two"),
        ("player", "chhotu", "Tum Chhotu ho? Saraswati ko jaante ho? Main uska pati hoon.",
         "तुम छोटू हो? सरस्वती को जानते हो? मैं उसका पति हूँ।", "", ""),
        ("chhotu", "player", "Saraswati didi? Haan! Woh roz mujhe vada pav khilati thi.",
         "सरस्वती दीदी? हाँ! वो रोज़ मुझे वड़ा पाव खिलाती थी।", "", ""),
        ("chhotu", "player", "Us din ek moti chain wala aadmi unke peeche pada tha. Bhau ka aadmi. Didi bhaag ke mandi ki taraf gayi.",
         "उस दिन एक मोटी चेन वाला आदमी उनके पीछे पड़ा था। भाऊ का आदमी। दीदी भाग के मंडी की तरफ़ गई।", "", "close"),
        ("player", "chhotu", "Bhau? Kaun Bhau?",
         "भाऊ? कौन भाऊ?", "", "close"),
        ("chhotu", "player", "Yahan ka dada. Sab usse darte hain. Didi Kamla mausi ke saath sabzi bechti thi. Chalo, main shortcut dikhata hoon!",
         "यहाँ का दादा। सब उससे डरते हैं। दीदी कमला मौसी के साथ सब्ज़ी बेचती थी। चलो, मैं शॉर्टकट दिखाता हूँ!", "Cheer", ""),
    ],
    "chhotu_arrive": [
        ("chhotu", "player", "Woh rahi Kamla mausi, sabzi ke thele pe. Main chalta hoon, mera match baaki hai!",
         "वो रही कमला मौसी, सब्ज़ी के ठेले पे। मैं चलता हूँ, मेरा मैच बाक़ी है!", "", "two"),
    ],
    "kamla": [
        ("kamla", "player", "Sabzi lo bhaiya, ekdum taazi hai! ...Kya? Saraswati?",
         "सब्ज़ी लो भैया, एकदम ताज़ी है! ...क्या? सरस्वती?", "", "two"),
        ("player", "kamla", "Main uska pati hoon, Shankar. Woh kahan hai mausi?",
         "मैं उसका पति हूँ, शंकर। वो कहाँ है मौसी?", "", ""),
        ("kamla", "player", "Bahut mehnati ladki hai. Mere saath thela lagaati thi. Paisa jod rahi thi, tumhare paas gaon lautne ke liye.",
         "बहुत मेहनती लड़की है। मेरे साथ ठेला लगाती थी। पैसा जोड़ रही थी, तुम्हारे पास गाँव लौटने के लिए।", "", ""),
        ("kamla", "player", "Par Bhau ne uska aadhaar card aur phone rakh liya. Bola, kiraya do, warna mere liye kaam karo.",
         "पर भाऊ ने उसका आधार कार्ड और फ़ोन रख लिया। बोला, किराया दो, वरना मेरे लिए काम करो।", "Angry", ""),
        ("player", "kamla", "Isliye uska phone nahi lag raha tha...",
         "इसलिए उसका फ़ोन नहीं लग रहा था...", "", "close"),
        ("kamla", "player", "Pappu chai wale ko sab ki khabar hoti hai. Main road pe tapri hai uski. Par dhyaan se, Bhau ke aadmi wahin baithte hain.",
         "पप्पू चाय वाले को सब की ख़बर होती है। मेन रोड पे टपरी है उसकी। पर ध्यान से, भाऊ के आदमी वहीं बैठते हैं।", "", ""),
    ],
    "pappu": [
        ("pappu", "player", "Ek cutting, garma garam! Naye lagte ho bhai, kahan se ho?",
         "एक कटिंग, गरमा गरम! नए लगते हो भाई, कहाँ से हो?", "", "two"),
        ("player", "pappu", "Gaon se. Apni biwi Saraswati ko dhoondh raha hoon. Bhau ke baare mein suna hai.",
         "गाँव से। अपनी बीवी सरस्वती को ढूँढ रहा हूँ। भाऊ के बारे में सुना है।", "", ""),
        ("pappu", "player", "Shhh! Dheere bolo! Woh dekho, laal shirt wala... Raghu. Bhau ka khaas aadmi.",
         "श्श्श! धीरे बोलो! वो देखो, लाल शर्ट वाला... रघु। भाऊ का ख़ास आदमी।", "", "close"),
        ("raghu", "goon", "Chal, Bhau ne pandal pe bulaya hai. Aaj raat hisaab hoga.",
         "चल, भाऊ ने पंडाल पे बुलाया है। आज रात हिसाब होगा।", "", "two"),
        ("pappu", "player", "Uske peeche jao. Par door se. Agar usne dekh liya, to tum bhi gaye aur Saraswati bhi.",
         "उसके पीछे जाओ। पर दूर से। अगर उसने देख लिया, तो तुम भी गए और सरस्वती भी।", "", "close"),
    ],
    "pandal": [
        ("bhau", "raghu", "Raghu! Woh ladki mili?",
         "रघु! वो लड़की मिली?", "", "wide"),
        ("raghu", "bhau", "Haan Bhau. Aaj raat das baje ki local se gaon bhaagne wali hai. Station pe.",
         "हाँ भाऊ। आज रात दस बजे की लोकल से गाँव भागने वाली है। स्टेशन पे।", "", ""),
        ("bhau", "raghu", "Bhaagegi? Mera teen mahine ka kiraya kaun dega? Station pe pakdo usse.",
         "भागेगी? मेरा तीन महीने का किराया कौन देगा? स्टेशन पे पकड़ो उसे।", "Angry", "close"),
        ("raghu", "bhau", "Aur woh gaon wala? Uska aadmi bhi aaya hua hai, sab se pooch raha hai.",
         "और वो गाँव वाला? उसका आदमी भी आया हुआ है, सब से पूछ रहा है।", "", ""),
        ("bhau", "raghu", "Usko bhi dekh lenge. Chalo.",
         "उसको भी देख लेंगे। चलो।", "", "close"),
        ("vo", "bhau", "Station... das baje. Mujhe unse pehle pahunchna hoga.",
         "स्टेशन... दस बजे। मुझे उनसे पहले पहुँचना होगा।", "", "close"),
    ],
    "finale": [
        ("saraswati", "player", "Shankar?! Tum... tum yahan?",
         "शंकर?! तुम... तुम यहाँ?", "", "close"),
        ("player", "saraswati", "Saraswati! Teen mahine... ek khabar to bhejti!",
         "सरस्वती! तीन महीने... एक ख़बर तो भेजती!", "", "two"),
        ("saraswati", "player", "Bhau ne mera phone, mera card, sab chheen liya tha. Main tumhare paas hi aa rahi thi, gaon.",
         "भाऊ ने मेरा फ़ोन, मेरा कार्ड, सब छीन लिया था। मैं तुम्हारे पास ही आ रही थी, गाँव।", "", ""),
        ("bhau", "player", "Itni jaldi kya hai, bahu? Pehle mera hisaab.",
         "इतनी जल्दी क्या है, बहू? पहले मेरा हिसाब।", "", "wide"),
        ("player", "bhau", "Uska jo bhi kiraya hai, main dunga. Par uska card aur phone wapas karo.",
         "उसका जो भी किराया है, मैं दूँगा। पर उसका कार्ड और फ़ोन वापस करो।", "Angry", ""),
        ("bhau", "player", "Aur agar na karoon to? Kya kar lega tu, gaon wale?",
         "और अगर न करूँ तो? क्या कर लेगा तू, गाँव वाले?", "Angry", "close"),
        ("lakshmi", "bhau", "Yeh akela nahi hai, Bhau. Hum sab iske saath hain. Poori basti dekh rahi hai.",
         "ये अकेला नहीं है, भाऊ। हम सब इसके साथ हैं। पूरी बस्ती देख रही है।", "", "wide"),
        ("kamla", "bhau", "Bahut hua tera dhanda!",
         "बहुत हुआ तेरा धंधा!", "Angry", ""),
        ("chhotu", "bhau", "Aur maine police ko phone kar diya hai!",
         "और मैंने पुलिस को फ़ोन कर दिया है!", "Cheer", ""),
        ("raghu", "bhau", "Bhau... police aa rahi hai. Nikalte hain.",
         "भाऊ... पुलिस आ रही है। निकलते हैं।", "", ""),
        ("bhau", "player", "Yeh le apna kaagaz. Agli baar nahi chhodunga.",
         "ये ले अपना काग़ज़। अगली बार नहीं छोड़ूँगा।", "Throw", "close"),
        ("saraswati", "player", "Shankar... chalo, ghar chalein.",
         "शंकर... चलो, घर चलें।", "", "close"),
        ("player", "saraswati", "Haan Saraswati. Ghar chalte hain.",
         "हाँ सरस्वती। घर चलते हैं।", "", "two"),
    ],
}
