#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "GIScatter.generated.h"

class UStaticMesh;
class UMaterialInterface;

/** One mesh placed many times. */
USTRUCT(BlueprintType)
struct FGIScatterItem
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") TObjectPtr<UStaticMesh> Mesh;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") TArray<FTransform> Transforms;
	/** Optional material overrides by slot index. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") TArray<TObjectPtr<UMaterialInterface>> Materials;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") bool bCollision = true;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") bool bCastShadow = true;
	/** 0 = never culled. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") float CullDistance = 0.f;
};

/**
 * Holds instanced static meshes generated by the level-building script. Components are rebuilt by
 * the construction script so the Python builder only has to fill `Items`.
 */
UCLASS()
class GTAINDIA_API AGIScatter : public AActor
{
	GENERATED_BODY()

public:
	AGIScatter();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Scatter") TArray<FGIScatterItem> Items;

	/** (Re)creates the instanced mesh components from Items. Called by the level builder. */
	UFUNCTION(CallInEditor, BlueprintCallable, Category = "Scatter")
	void BuildInstances();

protected:
	virtual void BeginPlay() override;

private:
	void CreateComponents(bool bPersistent);
};
